# Generated by Django 4.0.5 on 2022-06-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0003_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discounted_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
