# Generated by Django 4.0.5 on 2022-06-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0004_item_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test Description.'),
            preserve_default=False,
        ),
    ]
